//
//  ViewController.swift
//  Books
//
//  Created by Anna Horak on 21.12.2017.
//  Copyright © 2017 Anna Horak. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    var criminalBooks: [Book] = [
        Book(title: "\"Rzeka tajemnic\"", author: "Dennis Lehane", category: "kryminalne", description: "Historia trzech przyjaciół z dzieciństwa, których losy ponownie po kilkunastu latach splata morderstwo córki jednego z nich. Najlepsza powieść kryminalna, w której wątek morderstwa jest tylko pretekstem do zadania bardzo ważnych pytań o ludzką naturę i istotę zła. Rozbudowane rysy psychologiczne bohaterów, mocna i zapadająca w pamięci historia, która nie pozwala przejść obojętnie. Lehane między wierszami zdaje się zadawać pytanie: gdzie leży granica pomiędzy napastnikiem, ofiarą i wskazuje palcem problem społecznego napiętnowania.", price: 36.90, image: "rzeka_tajemnic"),
        Book(title: "\"Czerwony smok\"", author: "Thomas Harris", category: "kryminalne", description: "Pierwsza powieść Harrisa, w której pojawia się genialny zabójca Hannibal Lecter. Jest on jednak postacią drugoplanową, a głównym antagonistą jest morderca o pseudonimie Zębowa Wróżka. Powstrzymania psychopaty podejmuje się agent FBI, który kilka lat wcześniej aresztował właśnie Lectera. Barwni i niejednoznaczni bohaterowie oraz mocna, trzymająca w napięciu, a przy tym wyjątkowo brutalna historia sprawiają, że Harris zasłużył aby znaleźć się na tak wysokim miejscu w naszym zestawieniu.", price: 29.90, image: "czerwony_smok"),
        Book(title: "\"Wyspa tajemnic\"", author: "Dennis Lehane", category: "kryminalne", description: "Historia zakładu psychiatrycznego, do którego skierowani zostają dwaj agenci FBI, aby rozwiązać zagadkę zniknięcia jednej z pacjentek. Niestety po przybyciu na miejsce, pracowników i pensjonariuszy spowija zmowa milczenia, a do wyspy zbliża się huragan odcinając drogę ucieczki. Lehane operuje prostym językiem, aby ukazać bardzo złożoną i głęboką historię. Umiejętnie łączy elementy dreszczowca i kryminału, oddając w nasze ręce prawdziwy majstersztyk od początku do końca trzymający w napięciu.", price: 39.90, image: "wyspa_tajemnic"),
        Book(title: "\"Mężczyźni, którzy  nienawidzą kobiet\"", author: "Stieg Larsson", category: "kryminalne", description: "W 1966 roku bez śladu znika Harriet Vanger. Zakrojone jednak na szeroką skalę śledztwo nie przynosi rezultatu. Kilkadziesiąt lat po tych wydarzeniach dziennikarz śledczy Mikael Mlomkvist ponownie wraca do tej sprawy. To co udaje mu się odkryć przechodzi wszelkie pojęcie.  Mężczyźni, którzy nienawidzą kobiet to rozbudowany do granic, wielowątkowy i wielopokoleniowy kryminał o nienawiści, zbrodni oraz złu mieszkającym w człowieku. Larsson pyta nas - czy w cywilizowanym kraju może dochodzić do podobnych sytuacji, gdzie ludzie wykształceni, obyci i na poziomie, mogą w swoim wnętrzu kryć prawdziwą bestię, którą od czasu do czasu spuszcza się ze smyczy? ", price: 69.90, image: "mezczyzni"),
        Book(title: "\"Zaginiona dziewczyna\"", author: "Gillian Flynn", category: "kryminalne", description: "Nick i Amy obchodzą piątą rocznicę ślubu. Jednak zanim zdążą ją uczcić Amy znika z domu. Podejrzenie pada na Nicka, który dziwnie się zachowuje.  Prowadzone śledztwo coraz bardziej udowadnia jego winę. On sam zaś za wszelką cenę chce dowieźć swojej niewinności. Świetnie poprowadzona akcja, będąca swojego rodzaju grą z czytelnikiem. Zachwyca misternie budowana intryga, a autor udowadnia, że punkt widzenia zależy od punktu siedzenia.", price: 49.90, image: "zaginiona_dziewczyna"),
        Book(title: "\"Pan Mercedes\"", author: "Stephen King", category: "kryminalne", description: "Fabuła powieści Kinga zaczyna się  od bardzo mocnego uderzenia. W grupę ludzi oczekujących na targi pracy wjeżdża szaleniec Mercedesem, zabijając kilkanaście osób. Śledztwo niestety utyka w martwym punkcie. Po kilku miesiącach morderca nawiązuje kontakt z policjantem prowadzącym tę sprawę, który przebywa na emeryturze myśląc o samobójstwie. Sprawnie poprowadzony kryminał, z galerią barwnych postaci i rewelacyjnie poprowadzoną grą pomiędzy dwoma oponentami. King udowadnia, że w klimatach kryminalnych też czuje się bardzo bobrze. ", price: 69.90, image: "pan_mercedes"),
        Book(title: "\"Morderstwo w Orient Expressie\"", author: "Agatha Christie", category: "kryminalne", description: "Po rozwiązaniu sprawy kryminalnej w Azji Herkules Poirot wraca do Europy. Pociąg Orient Express, którym podróżuje, grzęźnie w zaspie śnieżnej. W nocy w niewyjaśnionych okolicznościach ginie jeden z pasażerów. Detektyw Poirot rozpoczyna dochodzenie. Sztandarowa powieść detektywistyczna, z której  do dzisiaj czerpie wenę wielu pisarzy tego gatunku. Intrygujące postacie, trudna zagadka i mnóstwo zaskakujących zwrotów akcji sprawia, że nie bez kozery autorkę nazywają królową kryminału.", price: 29.90, image: "morderstwo")
        ]
    
    
    var romanceBooks: [Book] = [
        Book(title: "\"Zanim się pojawiłeś\"", author: "Jojo Moyes", category: "romans", description: "Co robisz, jeśli chcesz uszczęśliwić osobę, którą kochasz, ale wiesz, że to złamie twoje serce? Jest wiele rzeczy, które wie ekscentryczna dwudziestosześciolatka Lou Clark. Wie, ile kroków dzieli przystanek autobusowy od jej domu. Wie, że lubi pracować w kawiarni Bułka z Masłem i że chyba nie kocha swojego chłopaka Patricka. Lou nie wie jednak, że za chwilę straci pracę i zostanie opiekunką młodego, bogatego bankiera, którego losy całkowicie zmieniły się na skutek tragicznego zdarzenia sprzed dwóch lat. \n Will Traynor wie, że wypadek motocyklowy odebrał mu chęć do życia. Wszystko wydaje mu się teraz błahe i pozbawione kolorów. Wie też, w jaki sposób to przerwać. Nie ma jednak pojęcia, że znajomość z Lou wywróci jego świat do góry nogami i odmieni ich oboje na zawsze.", price: 26.90, image: "rzeka_tajemnic"),
        Book(title: "\"It Ends with Us\"", author: "Colleen Hoover", category: "romans", description: "Czasem te osoby, które najmocniej nas kochają, potrafią też najmocniej ranić. \n Lily Bloom zawsze płynie pod prąd. Nic dziwnego, że otworzyła kwiaciarnię dla osób, które… nie lubią kwiatów, i prowadzi ją z pasją i sukcesami. Gdy poznaje przystojnego lekarza Ryle’a Kincaida i rodzi się między nimi wzajemna fascynacja, Lily jest przekonana, że jej życie nie może być już lepsze. \n Tak mogłaby skończyć się ta historia. Jednak niektóre rzeczy są zbyt piękne, by mogły trwać wiecznie. To, co się kryje za idealnym związkiem Lily i Ryle’a, jest w stanie dostrzec jedynie Atlas Corrigan, dawny przyjaciel Lily. Kiedyś ona była dla niego bezpieczną przystanią, teraz sama potrzebuje takiej pomocy. Nie zawsze jesteśmy bowiem dość odważni, by stanąć twarzą w twarz z prawdą… Szczególnie gdy przynosi ona tylko cierpienie.", price: 56.90, image: "it_ends"),
        Book(title: "\"Conviction\"", author: "Michaels Corinne", category: "romans", description: "Znakomita powieść dla fanek Colleen Hoover. Poruszająca historia, którą pokochały tysiące czytelniczek! \n Jeżeli myślisz, że zakończenie \"Consolation\" zwalało z nóg, przeczytaj \"Conviction\" i przekonaj się, że Corinne Michaels jest w stanie dostarczyć jeszcze większych emocji i zaskoczeń! Druga część duetu \"Consolation\" rozdziera serce, wzrusza i zachwyca, czyniąc tę literacką przygodę niezapomnianą i zapierającą dech w piersi. \n Po raz kolejny autorka złamie ci serce. Ale czy poskłada je na nowo?", price: 49.90, image: "conviction"),
        Book(title: "\"Confess\"", author: "Hoover Colleen", category: "romans", description: "Niewypowiedziane pragnienia, bolesna przeszłość i głęboko skrywane grzechy są dla Owena największą inspiracją. Utalentowany malarz kolekcjonuje anonimowe wyznania i przenosi je na płótno, zamieniając słowa w obrazy, w których ukrywa też własne tajemnice. \n Auburn pojawia się w jego galerii akurat wtedy, gdy Owen szuka asystentki. Dziewczyna od kilku lat walczy o odzyskanie normalnego życia i desperacko potrzebuje pieniędzy. Zakochanie się w przystojnym malarzu nie jest częścią jej planu, ale przekorne przeznaczenie stawia na swoim. Wydaje się, że Owen jest dla niej szansą na znalezienie ukojenia i wsparcia, a ona dla niego natchnieniem i nowym kolorem w autoportrecie. \n Wzajemne uczucie dodaje życiu barw, jednak tajemnice zaczynają tworzyć rysy na ich związku. Auburn odkrywa, że przeszłość ukochanego może odebrać jej to, co dla niej najważniejsze. Głos serca podpowiada jednak, że miłość wymaga największych poświęceń. ", price: 69.90, image: "confess"),
        Book(title: "\"Bez uczuć\"", author: "Sheridan Mia", category: "romans", description: "Nieszczęśliwa miłość do Lydii odebrała Broganowi wszystko. Ciężko zraniony staje się wyrachowany i skupia się na swoim biznesie i na zemście. Bo miłość wcale nie jest cierpliwa ani łaskawa. \n Życie Lydii wyglądało kiedyś zupełnie inaczej – była bogata, bezpieczna i kochana. Teraz fortuna się od niej odwróciła. Rodzinna firma znalazła się na skraju bankructwa, lecz Lydia zrobi wszytko, by ją uratować. Gdy na jaw stopniowo wychodzą tajemnice jej bliskich, dziewczyna odkrywa, że niebezpieczeństwo może grozić także jej. Nie przypuszcza jednak, że największy cios padnie z najmniej spodziewanej strony... \n Czy w sercach Lydii i Brogana na nowo zakwitnie miłość, chociaż wybrali życie bez uczuć?", price: 39.90, image: "bez_uczuc"),
        Book(title: "\"Love Line\"", author: "Reichter Nina", category: "romans", description: "Matthew Hansen - przystojny młody psycholog - doradza kobietom, jak zbudować satysfakcjonujący je związek i nie pozwolić sobą manipulować. \n Jest twórcą popularnej internetowej audycji LOVE Line, a jego charyzma  i celne rady przyciągają miliony słuchaczek. \n Zrządzeniem losu spotyka Bethany McCallum, będącą w trakcie rozwodu dziennikarkę luksusowego magazynu dla kobiet. Otrzymuje ona zlecenie napisania artykułu obnażającego metody stosowane przez hermetyczną grupę tak zwanych pick-up artists, czyli  trenerów podrywu. Nieetycznych manipulantów, którzy szkolą mężczyzn, jak zaciągnąć kobiety do łóżka. \n Ich drogi krzyżują się przy stoliku pewnej bardzo nietypowej restauracji. Wzajemne przyciąganie sprawia, że Matt postanawia zbliżyć się do Bethany. Aby to zrobić, będzie musiał podzielić się z nią swoją wiedzą.", price: 32.90, image: "love_line"),
        Book(title: "\"Salon sukni ślubnych\"", author: "Hauck Rachel", category: "romans", description: "Dwie główne bohaterki i dwie niezwykłe historie o pracy, spełnianiu marzeń, zauroczeniu i miłości – tej chorej, obezwładniającej, niszczącej od wewnątrz, i tej prawdziwej, niosącej spełnienie. No i zaskakujące zakończenie… \n Początek lat trzydziestych XX wieku. Cora Scott odważnie kroczy ścieżką kariery, prowadząc w Heart’s Bend w Tennessee salon sukien ślubnych. Panny młode przyjeżdżają aż z samego Birmingham, by dzięki Corze poczuć się wyjątkowo. Po śmierci właścicielki salon popada w ruinę. O przywrócenie go do stanu pierwotnego postanawia zawalczyć na początku XXI wieku kapitan Haley Morgan, która po odejściu ze służby w siłach powietrznych USA wraca ze złamanym sercem do rodzinnego miasteczka. Odżywają dawne wspomnienia i pewna obietnica.", price: 48.90, image: "salon"),
        Book(title: "\"Bez szans\"", author: "Sheridan Mia", category: "romans", description: "W upadającym górskim miasteczku Kyland i Ten zakochują się w sobie wbrew rozsądkowi i na przekór surowej rzeczywistości. Kyland marzy tylko o tym, by przetrwać. Zaciska zęby i robi wszystko, by nie pokonała go bieda i samotność. Nie szuka miłości. Nie zamierza też oglądać się za siebie, gdy uda mu się wyrwać z piekła, w którym przyszło mu dorastać. Dla Ten codzienność to nieustanna walka o własną godność. Zmagania z chorobą matki i ludzką nieprzychylnością wymagają od niej wyjątkowej siły. Oboje rywalizują o bilet do lepszego życia, który może otrzymać tylko jedno z nich. Ktoś odejdzie, ktoś zostanie. Czy po latach zdołają spojrzeć sobie w oczy, jeśli poświęcą miłość dla przetrwania?", price: 35.49, image: "bez_szans"),
        Book(title: "\"W blasku reflektorów\"", author: "Roberts Nora", category: "romans", description: "Kłamstwa i tajemnice. Dziennikarz Dylan Crosby zamierza napisać biografię słynnego kierowcy rajdowego, Chucka Rockwella, który zginął tragicznie w wypadku. Umawia się na serię rozmów z wdową po Rockwellu, Abby. Pełen uprzedzeń, spodziewa się spotkać bogatą i bezwzględną kobietę. Tymczasem Abby bardzo odbiega od jego wyobrażeń. Ciężko pracuje, by utrzymać siebie i dwóch synów. Z czasem zaczyna coraz chętniej opowiadać o zmarłym mężu, ale Dylan wyczuwa, że nie mówi całej prawdy. Roztańczone życie. Maddy  O’Hurley, tancerka i piosenkarka, pewnego dnia zostaje napadnięta na ulicy. Ratuje ją Reed Valentine, wpływowy właściciel firmy fonograficznej. Impulsywna artystka i pełen rezerwy biznesmen są jak ogień i woda. Mimo to wzajemna fascynacja nie pozwala im o sobie zapomnieć, chociaż każde z nich zupełnie inaczej wyobraża sobie związek dwojga ludzi.", price: 35.49, image: "blask"),
        Book(title: "\"Tajemnice diamentów\"", author: "Galen Shana", category: "romans", description: "Miał idealnie uporządkowane życie… William, książę Pelham, lubi swoje zorganizowane, przewidywalne życie. Dlaczego więc staje się nagle obiektem ataków? Plotkarska prasa przypisuje mu romans z Juliette, jedną z najpiękniejszych i najbardziej tajemniczych londyńskich kurtyzan. Poukładany świat Williama pogrąża się nieopisanym chaosie dopóki nie pojawiła się ona. Juliette, zwana Księżną Zalotów, ma u stóp najpotężniejszych arystokratów. Nie jest więc zachwycona, że książę Pelham jako jej rzekomy kochanek odstrasza od niej wielbicieli. Oboje muszą oczyścić swoje imię. A to oznacza, że odkryją swoje sekrety i narażą się na niebezpieczeństwo stokroć większe niż towarzyski skandal…", price: 45.99, image: "tajemnice"),
        Book(title: "\"Gwiazdy fortuny \"", author: "Roberts Nora", category: "romans", description: "Sasha Riggs maluje niesamowite obrazy, pełne dziwacznych postaci i koszmarów, które dręczą ją w snach. Pod wpływem swoich wizji udaje się na grecką wyspę Korfu. Spotyka tu pięcioro młodych ludzi obdarzonych nadprzyrodzonymi zdolnościami. Muszą połączyć siły, by uratować świat przed zagrażającym mu niebezpieczeństwem. Sasha próbuje walczyć ze swoim przeznaczeniem. Jej towarzysz, obdarzony czarnoksięską mocą Bran, pomaga dziewczynie uwierzyć w siebie i razem z pozostałą czwórką rozpoczynają poszukiwania gwiazdy ognia, ukrytej w podmorskiej jaskini. Tuż obok nich czai się jednak ktoś, kto uczyni wszystko, byle tylko im przeszkodzić. Rozpoczyna się wielka próba...", price: 55.49, image: "gwiazdy")
    ]
    
    var biographyBooks: [Book] = [
        Book(title: "\"Zanim się pojawiłeś\"", author: "Jojo Moyes", category: "romans", description: "Co robisz, jeśli chcesz uszczęśliwić osobę, którą kochasz, ale wiesz, że to złamie twoje serce? Jest wiele rzeczy, które wie ekscentryczna dwudziestosześciolatka Lou Clark. Wie, ile kroków dzieli przystanek autobusowy od jej domu. Wie, że lubi pracować w kawiarni Bułka z Masłem i że chyba nie kocha swojego chłopaka Patricka. Lou nie wie jednak, że za chwilę straci pracę i zostanie opiekunką młodego, bogatego bankiera, którego losy całkowicie zmieniły się na skutek tragicznego zdarzenia sprzed dwóch lat. \n Will Traynor wie, że wypadek motocyklowy odebrał mu chęć do życia. Wszystko wydaje mu się teraz błahe i pozbawione kolorów. Wie też, w jaki sposób to przerwać. Nie ma jednak pojęcia, że znajomość z Lou wywróci jego świat do góry nogami i odmieni ich oboje na zawsze.", price: 26.90, image: "rzeka_tajemnic"),
        Book(title: "\"It Ends with Us\"", author: "Colleen Hoover", category: "romans", description: "Czasem te osoby, które najmocniej nas kochają, potrafią też najmocniej ranić. \n Lily Bloom zawsze płynie pod prąd. Nic dziwnego, że otworzyła kwiaciarnię dla osób, które… nie lubią kwiatów, i prowadzi ją z pasją i sukcesami. Gdy poznaje przystojnego lekarza Ryle’a Kincaida i rodzi się między nimi wzajemna fascynacja, Lily jest przekonana, że jej życie nie może być już lepsze. \n Tak mogłaby skończyć się ta historia. Jednak niektóre rzeczy są zbyt piękne, by mogły trwać wiecznie. To, co się kryje za idealnym związkiem Lily i Ryle’a, jest w stanie dostrzec jedynie Atlas Corrigan, dawny przyjaciel Lily. Kiedyś ona była dla niego bezpieczną przystanią, teraz sama potrzebuje takiej pomocy. Nie zawsze jesteśmy bowiem dość odważni, by stanąć twarzą w twarz z prawdą… Szczególnie gdy przynosi ona tylko cierpienie.", price: 56.90, image: "it_ends"),
        Book(title: "\"Conviction\"", author: "Michaels Corinne", category: "romans", description: "Znakomita powieść dla fanek Colleen Hoover. Poruszająca historia, którą pokochały tysiące czytelniczek! \n Jeżeli myślisz, że zakończenie \"Consolation\" zwalało z nóg, przeczytaj \"Conviction\" i przekonaj się, że Corinne Michaels jest w stanie dostarczyć jeszcze większych emocji i zaskoczeń! Druga część duetu \"Consolation\" rozdziera serce, wzrusza i zachwyca, czyniąc tę literacką przygodę niezapomnianą i zapierającą dech w piersi. \n Po raz kolejny autorka złamie ci serce. Ale czy poskłada je na nowo?", price: 49.90, image: "conviction"),
        Book(title: "\"Confess\"", author: "Hoover Colleen", category: "romans", description: "Niewypowiedziane pragnienia, bolesna przeszłość i głęboko skrywane grzechy są dla Owena największą inspiracją. Utalentowany malarz kolekcjonuje anonimowe wyznania i przenosi je na płótno, zamieniając słowa w obrazy, w których ukrywa też własne tajemnice. \n Auburn pojawia się w jego galerii akurat wtedy, gdy Owen szuka asystentki. Dziewczyna od kilku lat walczy o odzyskanie normalnego życia i desperacko potrzebuje pieniędzy. Zakochanie się w przystojnym malarzu nie jest częścią jej planu, ale przekorne przeznaczenie stawia na swoim. Wydaje się, że Owen jest dla niej szansą na znalezienie ukojenia i wsparcia, a ona dla niego natchnieniem i nowym kolorem w autoportrecie. \n Wzajemne uczucie dodaje życiu barw, jednak tajemnice zaczynają tworzyć rysy na ich związku. Auburn odkrywa, że przeszłość ukochanego może odebrać jej to, co dla niej najważniejsze. Głos serca podpowiada jednak, że miłość wymaga największych poświęceń. ", price: 69.90, image: "confess"),
        Book(title: "\"Bez uczuć\"", author: "Sheridan Mia", category: "romans", description: "Nieszczęśliwa miłość do Lydii odebrała Broganowi wszystko. Ciężko zraniony staje się wyrachowany i skupia się na swoim biznesie i na zemście. Bo miłość wcale nie jest cierpliwa ani łaskawa. \n Życie Lydii wyglądało kiedyś zupełnie inaczej – była bogata, bezpieczna i kochana. Teraz fortuna się od niej odwróciła. Rodzinna firma znalazła się na skraju bankructwa, lecz Lydia zrobi wszytko, by ją uratować. Gdy na jaw stopniowo wychodzą tajemnice jej bliskich, dziewczyna odkrywa, że niebezpieczeństwo może grozić także jej. Nie przypuszcza jednak, że największy cios padnie z najmniej spodziewanej strony... \n Czy w sercach Lydii i Brogana na nowo zakwitnie miłość, chociaż wybrali życie bez uczuć?", price: 39.90, image: "bez_uczuc"),
        Book(title: "\"Love Line\"", author: "Reichter Nina", category: "romans", description: "Matthew Hansen - przystojny młody psycholog - doradza kobietom, jak zbudować satysfakcjonujący je związek i nie pozwolić sobą manipulować. \n Jest twórcą popularnej internetowej audycji LOVE Line, a jego charyzma  i celne rady przyciągają miliony słuchaczek. \n Zrządzeniem losu spotyka Bethany McCallum, będącą w trakcie rozwodu dziennikarkę luksusowego magazynu dla kobiet. Otrzymuje ona zlecenie napisania artykułu obnażającego metody stosowane przez hermetyczną grupę tak zwanych pick-up artists, czyli  trenerów podrywu. Nieetycznych manipulantów, którzy szkolą mężczyzn, jak zaciągnąć kobiety do łóżka. \n Ich drogi krzyżują się przy stoliku pewnej bardzo nietypowej restauracji. Wzajemne przyciąganie sprawia, że Matt postanawia zbliżyć się do Bethany. Aby to zrobić, będzie musiał podzielić się z nią swoją wiedzą.", price: 32.90, image: "love_line"),
        Book(title: "\"Salon sukni ślubnych\"", author: "Hauck Rachel", category: "romans", description: "Dwie główne bohaterki i dwie niezwykłe historie o pracy, spełnianiu marzeń, zauroczeniu i miłości – tej chorej, obezwładniającej, niszczącej od wewnątrz, i tej prawdziwej, niosącej spełnienie. No i zaskakujące zakończenie… \n Początek lat trzydziestych XX wieku. Cora Scott odważnie kroczy ścieżką kariery, prowadząc w Heart’s Bend w Tennessee salon sukien ślubnych. Panny młode przyjeżdżają aż z samego Birmingham, by dzięki Corze poczuć się wyjątkowo. Po śmierci właścicielki salon popada w ruinę. O przywrócenie go do stanu pierwotnego postanawia zawalczyć na początku XXI wieku kapitan Haley Morgan, która po odejściu ze służby w siłach powietrznych USA wraca ze złamanym sercem do rodzinnego miasteczka. Odżywają dawne wspomnienia i pewna obietnica.", price: 48.90, image: "salon"),
    ]
    
    var fantasyBooks: [Book] = [
        Book(title: "\"Zanim się pojawiłeś\"", author: "Jojo Moyes", category: "romans", description: "Co robisz, jeśli chcesz uszczęśliwić osobę, którą kochasz, ale wiesz, że to złamie twoje serce? Jest wiele rzeczy, które wie ekscentryczna dwudziestosześciolatka Lou Clark. Wie, ile kroków dzieli przystanek autobusowy od jej domu. Wie, że lubi pracować w kawiarni Bułka z Masłem i że chyba nie kocha swojego chłopaka Patricka. Lou nie wie jednak, że za chwilę straci pracę i zostanie opiekunką młodego, bogatego bankiera, którego losy całkowicie zmieniły się na skutek tragicznego zdarzenia sprzed dwóch lat. \n Will Traynor wie, że wypadek motocyklowy odebrał mu chęć do życia. Wszystko wydaje mu się teraz błahe i pozbawione kolorów. Wie też, w jaki sposób to przerwać. Nie ma jednak pojęcia, że znajomość z Lou wywróci jego świat do góry nogami i odmieni ich oboje na zawsze.", price: 26.90, image: "rzeka_tajemnic"),
        Book(title: "\"It Ends with Us\"", author: "Colleen Hoover", category: "romans", description: "Czasem te osoby, które najmocniej nas kochają, potrafią też najmocniej ranić. \n Lily Bloom zawsze płynie pod prąd. Nic dziwnego, że otworzyła kwiaciarnię dla osób, które… nie lubią kwiatów, i prowadzi ją z pasją i sukcesami. Gdy poznaje przystojnego lekarza Ryle’a Kincaida i rodzi się między nimi wzajemna fascynacja, Lily jest przekonana, że jej życie nie może być już lepsze. \n Tak mogłaby skończyć się ta historia. Jednak niektóre rzeczy są zbyt piękne, by mogły trwać wiecznie. To, co się kryje za idealnym związkiem Lily i Ryle’a, jest w stanie dostrzec jedynie Atlas Corrigan, dawny przyjaciel Lily. Kiedyś ona była dla niego bezpieczną przystanią, teraz sama potrzebuje takiej pomocy. Nie zawsze jesteśmy bowiem dość odważni, by stanąć twarzą w twarz z prawdą… Szczególnie gdy przynosi ona tylko cierpienie.", price: 56.90, image: "it_ends"),
        Book(title: "\"Conviction\"", author: "Michaels Corinne", category: "romans", description: "Znakomita powieść dla fanek Colleen Hoover. Poruszająca historia, którą pokochały tysiące czytelniczek! \n Jeżeli myślisz, że zakończenie \"Consolation\" zwalało z nóg, przeczytaj \"Conviction\" i przekonaj się, że Corinne Michaels jest w stanie dostarczyć jeszcze większych emocji i zaskoczeń! Druga część duetu \"Consolation\" rozdziera serce, wzrusza i zachwyca, czyniąc tę literacką przygodę niezapomnianą i zapierającą dech w piersi. \n Po raz kolejny autorka złamie ci serce. Ale czy poskłada je na nowo?", price: 49.90, image: "conviction"),
        Book(title: "\"Confess\"", author: "Hoover Colleen", category: "romans", description: "Niewypowiedziane pragnienia, bolesna przeszłość i głęboko skrywane grzechy są dla Owena największą inspiracją. Utalentowany malarz kolekcjonuje anonimowe wyznania i przenosi je na płótno, zamieniając słowa w obrazy, w których ukrywa też własne tajemnice. \n Auburn pojawia się w jego galerii akurat wtedy, gdy Owen szuka asystentki. Dziewczyna od kilku lat walczy o odzyskanie normalnego życia i desperacko potrzebuje pieniędzy. Zakochanie się w przystojnym malarzu nie jest częścią jej planu, ale przekorne przeznaczenie stawia na swoim. Wydaje się, że Owen jest dla niej szansą na znalezienie ukojenia i wsparcia, a ona dla niego natchnieniem i nowym kolorem w autoportrecie. \n Wzajemne uczucie dodaje życiu barw, jednak tajemnice zaczynają tworzyć rysy na ich związku. Auburn odkrywa, że przeszłość ukochanego może odebrać jej to, co dla niej najważniejsze. Głos serca podpowiada jednak, że miłość wymaga największych poświęceń. ", price: 69.90, image: "confess"),
        Book(title: "\"Bez uczuć\"", author: "Sheridan Mia", category: "romans", description: "Nieszczęśliwa miłość do Lydii odebrała Broganowi wszystko. Ciężko zraniony staje się wyrachowany i skupia się na swoim biznesie i na zemście. Bo miłość wcale nie jest cierpliwa ani łaskawa. \n Życie Lydii wyglądało kiedyś zupełnie inaczej – była bogata, bezpieczna i kochana. Teraz fortuna się od niej odwróciła. Rodzinna firma znalazła się na skraju bankructwa, lecz Lydia zrobi wszytko, by ją uratować. Gdy na jaw stopniowo wychodzą tajemnice jej bliskich, dziewczyna odkrywa, że niebezpieczeństwo może grozić także jej. Nie przypuszcza jednak, że największy cios padnie z najmniej spodziewanej strony... \n Czy w sercach Lydii i Brogana na nowo zakwitnie miłość, chociaż wybrali życie bez uczuć?", price: 39.90, image: "bez_uczuc"),
        Book(title: "\"Love Line\"", author: "Reichter Nina", category: "romans", description: "Matthew Hansen - przystojny młody psycholog - doradza kobietom, jak zbudować satysfakcjonujący je związek i nie pozwolić sobą manipulować. \n Jest twórcą popularnej internetowej audycji LOVE Line, a jego charyzma  i celne rady przyciągają miliony słuchaczek. \n Zrządzeniem losu spotyka Bethany McCallum, będącą w trakcie rozwodu dziennikarkę luksusowego magazynu dla kobiet. Otrzymuje ona zlecenie napisania artykułu obnażającego metody stosowane przez hermetyczną grupę tak zwanych pick-up artists, czyli  trenerów podrywu. Nieetycznych manipulantów, którzy szkolą mężczyzn, jak zaciągnąć kobiety do łóżka. \n Ich drogi krzyżują się przy stoliku pewnej bardzo nietypowej restauracji. Wzajemne przyciąganie sprawia, że Matt postanawia zbliżyć się do Bethany. Aby to zrobić, będzie musiał podzielić się z nią swoją wiedzą.", price: 32.90, image: "love_line"),
        Book(title: "\"Salon sukni ślubnych\"", author: "Hauck Rachel", category: "romans", description: "Dwie główne bohaterki i dwie niezwykłe historie o pracy, spełnianiu marzeń, zauroczeniu i miłości – tej chorej, obezwładniającej, niszczącej od wewnątrz, i tej prawdziwej, niosącej spełnienie. No i zaskakujące zakończenie… \n Początek lat trzydziestych XX wieku. Cora Scott odważnie kroczy ścieżką kariery, prowadząc w Heart’s Bend w Tennessee salon sukien ślubnych. Panny młode przyjeżdżają aż z samego Birmingham, by dzięki Corze poczuć się wyjątkowo. Po śmierci właścicielki salon popada w ruinę. O przywrócenie go do stanu pierwotnego postanawia zawalczyć na początku XXI wieku kapitan Haley Morgan, która po odejściu ze służby w siłach powietrznych USA wraca ze złamanym sercem do rodzinnego miasteczka. Odżywają dawne wspomnienia i pewna obietnica.", price: 48.90, image: "salon"),
        Book(title: "\"Bez szans\"", author: "Sheridan Mia", category: "romans", description: "W upadającym górskim miasteczku Kyland i Ten zakochują się w sobie wbrew rozsądkowi i na przekór surowej rzeczywistości. Kyland marzy tylko o tym, by przetrwać. Zaciska zęby i robi wszystko, by nie pokonała go bieda i samotność. Nie szuka miłości. Nie zamierza też oglądać się za siebie, gdy uda mu się wyrwać z piekła, w którym przyszło mu dorastać. Dla Ten codzienność to nieustanna walka o własną godność. Zmagania z chorobą matki i ludzką nieprzychylnością wymagają od niej wyjątkowej siły. Oboje rywalizują o bilet do lepszego życia, który może otrzymać tylko jedno z nich. Ktoś odejdzie, ktoś zostanie. Czy po latach zdołają spojrzeć sobie w oczy, jeśli poświęcą miłość dla przetrwania?", price: 35.49, image: "bez_szans"),
        Book(title: "\"W blasku reflektorów\"", author: "Roberts Nora", category: "romans", description: "Kłamstwa i tajemnice. Dziennikarz Dylan Crosby zamierza napisać biografię słynnego kierowcy rajdowego, Chucka Rockwella, który zginął tragicznie w wypadku. Umawia się na serię rozmów z wdową po Rockwellu, Abby. Pełen uprzedzeń, spodziewa się spotkać bogatą i bezwzględną kobietę. Tymczasem Abby bardzo odbiega od jego wyobrażeń. Ciężko pracuje, by utrzymać siebie i dwóch synów. Z czasem zaczyna coraz chętniej opowiadać o zmarłym mężu, ale Dylan wyczuwa, że nie mówi całej prawdy. Roztańczone życie. Maddy  O’Hurley, tancerka i piosenkarka, pewnego dnia zostaje napadnięta na ulicy. Ratuje ją Reed Valentine, wpływowy właściciel firmy fonograficznej. Impulsywna artystka i pełen rezerwy biznesmen są jak ogień i woda. Mimo to wzajemna fascynacja nie pozwala im o sobie zapomnieć, chociaż każde z nich zupełnie inaczej wyobraża sobie związek dwojga ludzi.", price: 35.49, image: "blask"),
        Book(title: "\"Tajemnice diamentów\"", author: "Galen Shana", category: "romans", description: "Miał idealnie uporządkowane życie… William, książę Pelham, lubi swoje zorganizowane, przewidywalne życie. Dlaczego więc staje się nagle obiektem ataków? Plotkarska prasa przypisuje mu romans z Juliette, jedną z najpiękniejszych i najbardziej tajemniczych londyńskich kurtyzan. Poukładany świat Williama pogrąża się nieopisanym chaosie dopóki nie pojawiła się ona. Juliette, zwana Księżną Zalotów, ma u stóp najpotężniejszych arystokratów. Nie jest więc zachwycona, że książę Pelham jako jej rzekomy kochanek odstrasza od niej wielbicieli. Oboje muszą oczyścić swoje imię. A to oznacza, że odkryją swoje sekrety i narażą się na niebezpieczeństwo stokroć większe niż towarzyski skandal…", price: 45.99, image: "tajemnice"),
        Book(title: "\"Gwiazdy fortuny \"", author: "Roberts Nora", category: "romans", description: "Sasha Riggs maluje niesamowite obrazy, pełne dziwacznych postaci i koszmarów, które dręczą ją w snach. Pod wpływem swoich wizji udaje się na grecką wyspę Korfu. Spotyka tu pięcioro młodych ludzi obdarzonych nadprzyrodzonymi zdolnościami. Muszą połączyć siły, by uratować świat przed zagrażającym mu niebezpieczeństwem. Sasha próbuje walczyć ze swoim przeznaczeniem. Jej towarzysz, obdarzony czarnoksięską mocą Bran, pomaga dziewczynie uwierzyć w siebie i razem z pozostałą czwórką rozpoczynają poszukiwania gwiazdy ognia, ukrytej w podmorskiej jaskini. Tuż obok nich czai się jednak ktoś, kto uczyni wszystko, byle tylko im przeszkodzić. Rozpoczyna się wielka próba...", price: 55.49, image: "gwiazdy")
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "kryminalne" {
            let destinationController = segue.destination as! BookTableViewController
            destinationController.books = criminalBooks
        }
        if segue.identifier == "romanse" {
            let destinationController = segue.destination as! BookTableViewController
            destinationController.books = romanceBooks
        }
        if segue.identifier == "biografie" {
            let destinationController = segue.destination as! BookTableViewController
            destinationController.books = biographyBooks
        }
        if segue.identifier == "horrory" {
            let destinationController = segue.destination as! BookTableViewController
            destinationController.books = fantasyBooks
        }
    }
}

